spring.application.name=${APPLICATION_NAME}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=${DATASOURCE-DRIVER-CLASS-NAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1000MB
